### ISSUE TITLE
Exception when using saveAndLoad method

### ISSUE THREAD

**Issue by mluizaa00** [cefoler/configuration#3]
After using the saveAndLoad method, the following error has been throwed and the configuration was corrupted
```

[21:01:28 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[21:01:28 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[21:01:28 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
[21:01:28 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[21:01:28 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[21:01:28 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[21:01:28 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[21:01:28 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[21:01:28 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[21:01:28 WARN]:        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[21:01:28 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[21:01:28 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[21:01:28 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[21:01:28 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[21:01:28 WARN]:        at java.lang.Thread.run(Thread.java:748)
[21:01:28 WARN]: Caused by: com.celeste.configuration.model.exception.FailedSaveException: java.lang.NoSuchMethodError: org.yaml.snakeyaml.events.MappingStartEvent.<init>(Ljava/lang/String;Ljava/lang/String;ZLorg/yaml/snakeyaml/error/Mark;Lorg/yaml/snakeyaml/error/Mark;Lorg/yaml/snakeyaml/DumperOptions$FlowStyle;)V
[21:01:28 WARN]:        at com.celeste.configuration.model.provider.AbstractConfiguration.save(AbstractConfiguration.java:112)
[21:01:28 WARN]:        at com.celeste.configuration.model.provider.AbstractConfiguration.saveAndLoad(AbstractConfiguration.java:124)
[21:01:28 WARN]:        at com.celeste.lobby.views.command.ReloadCommand.handleCommand(ReloadCommand.java:31)
[21:01:28 WARN]:        ... 22 more
[21:01:28 WARN]: Caused by: java.lang.NoSuchMethodError: org.yaml.snakeyaml.events.MappingStartEvent.<init>(Ljava/lang/String;Ljava/lang/String;ZLorg/yaml/snakeyaml/error/Mark;Lorg/yaml/snakeyaml/error/Mark;Lorg/yaml/snakeyaml/DumperOptions$FlowStyle;)V
[21:01:28 WARN]:        at com.fasterxml.jackson.dataformat.yaml.YAMLGenerator.writeStartObject(YAMLGenerator.java:555)
[21:01:28 WARN]:        at com.fasterxml.jackson.core.base.GeneratorBase.writeStartObject(GeneratorBase.java:294)
[21:01:28 WARN]:        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:719)
[21:01:28 WARN]:        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:35)
[21:01:28 WARN]:        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
[21:01:28 WARN]:        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
[21:01:28 WARN]:        at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1514)
[21:01:28 WARN]:        at com.fasterxml.jackson.databind.ObjectWriter._writeValueAndClose(ObjectWriter.java:1215)
[21:01:28 WARN]:        at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:1059)
[21:01:28 WARN]:        at com.celeste.configuration.model.provider.AbstractConfiguration.save(AbstractConfiguration.java:110)
[21:01:28 WARN]:        ... 24 more
```

**Comment by DeserRC** [comment]
This error has already been resolved in the version 1.0.1 update
